### ISSUE TITLE
Request table update

### ISSUE THREAD

**Issue by 112roel** [OttoKaaij/ottokaaij.github.io#2]
Request table update at: [ottokaaij.nl/our-house](ottokaaij.nl/our-house) 

`<table>
  <thead>
    <tr>
      <th>Partij</th>
      <th>Muzikant</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Keys 1</td>
      <td>Carly</td>
    </tr>
    <tr>
      <td>Keys 2</td>
      <td>Otto</td>
    </tr>
    <tr>
      <td>Gitaar</td>
      <td>Roel</td>
    </tr>
    <tr>
      <td>Basgitaar</td>
      <td>?</td>
    </tr>
    <tr>
      <td>Drums</td>
      <td>Jonah</td>
    </tr>
    <tr>
      <td>Trompet</td>
      <td>?</td>
    </tr>
    <tr>
      <td>Sax, Klarinet, Fluit</td>
      <td>Hugo</td>
    </tr>
  </tbody>
</table>`

**Comment by OttoKaaij** [comment]
Fixed in 6acefbc91e
